# Generated by Django 3.0 on 2022-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='variants',
            field=models.ManyToManyField(to='bets.Variant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsubcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
