# Generated by Django 3.0 on 2022-09-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20220831_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Event'),
        ),
        migrations.AlterField(
            model_name='betvariant',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Bet'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.EventStatus'),
        ),
    ]
